export const sportNmaes = [
    'Alpine Skiing',
    'Archery',
    'Athletics',
    'Badminton',
    'Bandy',
    'Baseball',
    'Basketball',
    'Beach Volleyball',
    'Biathlon',
    'Bobsleigh',
    'Bowls',
    'Boxing',
    'Bridge',
    'Chess',
    'Cricket',
    'Crossfit',
    'Curling',
    'Cycling',
    'Darts',
    'Entertainment',
    'Field Hockey',
    'Figure Skating',
    'Floorball',
    'Football',
    'Futsal',
    'Golf',
    'Handball',
    'Hockey',
    'Horse Racing',
    'Kabaddi',
    'Lacrosse',
    'Luge',
    'Martial Arts',
    'Motor',
    'Netball',
    'Olympics',
    'Poker',
    'Politics',
    'Pool',
    'Racing',
    'Rowing',
    'Rugby',
    'Skeleton',
    'Ski Jumping',
    'Snooker',
    'Snow Boarding',
    'Soccer',
    'Softball',
    'Speed Skating',
    'Squash',
    'Sumo',
    'Table Tennis',
    'Tennis',
    'Volleyball',
    'Water Polo',
    'Yachting'  
];